using Database.Models.DTOs;
using Database.Repositories.Interfaces;
using Database.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Server.Controllers
{
    [Route("api/messages")]
    [ApiController]
    public class MessagesController : ControllerBase
    {
        private readonly IAIRepository _aiRepository;

        public MessagesController(IAIRepository aiRepository)
        {
            _aiRepository = aiRepository;
        }


        /// <summary>
        /// Chat with AI
        /// </summary>
        /// <param name="request">Given request to send to Gemini AI.</param>
        /// <returns>Returns a responed generated by AI.</returns>
        [HttpPost("ChatWithAI")]
        public async Task<IActionResult> ChatWithAI([FromBody] GeminiRequestDTO request)
        {
            try
            {
                var UserId = UserService.ExtractUserIDFromToken(Request.Headers["Authorization"].FirstOrDefault()?.Split(" ").Last());
                var GeneratedPost = await _aiRepository.ChatWithAI(request, UserId);

                return Ok(GeneratedPost);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }

    }
}
